env = { TOOLS_DATA_DIR="%GRIP_ROOT_PATH%/temp_data" }
doc = """
The toolchains repository is a make environment for downloading,
configuring, compiling and installing the GNU toolchain and binutils,
as cross-compilers.

It has three grip stages: download, configure and install. The underlying
git repo will perform all downloading during the download stage - after that
is complete the network is not required for a built.
"""

[download]
exec = "make DATA_DIR=%TOOLS_DATA_DIR% INSTALL_DIR=%TOOLS_DIR% download"

[configure]
requires = ["download"]
exec = "make TARGET=riscv32-elf DATA_DIR=%TOOLS_DATA_DIR% INSTALL_DIR=%TOOLS_DIR% configure"

[install]
requires = ["configure"]
exec = "make TARGET=riscv32-elf DATA_DIR=%TOOLS_DATA_DIR% INSTALL_DIR=%TOOLS_DIR% install"

